
##H2Database
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop  #h2데이터베이스 속성
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver


##MySQL
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/SOMANG?serverTimezone=Asia/Seoul
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver



  ##ORACLE
spring:
  datasource:
    url: jdbc:oracle:thin:@10.211.55.3:1521:xe
    username: SOMANG
    password: SOMANG
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

